services:
  accounts:
    image: "imbuka/accounts:newone"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - imbuka
  cards:
    image: "imbuka/cards:newcards"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - imbuka
  loans:
    image: "imbuka/loans:newloans"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - imbuka
networks:
  imbuka:
    driver: "bridge"