spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

accounts:
  message: "Welcome to Benki loans related Prod APIs "
  contactDetails:
    name: "Stella Wambo - Product Owner"
    email: "stella@benki.com"
  onCallSupport:
    - (254) 888-1234
    - (254) 888-1345