spring:
  application:
    name: "configserver"
  profiles:
    active: git
  # active: native

  cloud:
    config:
      server:
        git:
          uri: "https://github.com/Alvinimbua/imbuka-config.git"
        #native:
         # search-locations: "file:///home//ialvin//Documents//config"
          default-label: master
          timeout: 5
          clone-on-start: true
          force-pull: true
  #  bus:
     # enabled: true
    # search-locations: "classpath:/config"
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

server:
  port: 8071

encrypt:
  key: "bti4EHVKs0xrRZ8NJ0lxf5TctkDdyLF4+iImUEOJj0I="

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true